### ISSUE TITLE
support . in name of key

### ISSUE THREAD

**Issue by tshepang** [ramn/enw#2]
I saw it's not supported, and I only ask because dotenv supports it, so would make this tool more complete.

https://github.com/ramn/enw/blob/a5b43de133653d39453933f468e7d14a1fc5a938/src/lib.rs#L127

**Comment by ramn** [comment]
What do you think about https://github.com/ramn/enw/pull/3

**Comment by tshepang** [comment]
it feels broad, but I also don't know what the harm is... spec is very loose

let's do it!
